extends: default

ignore: |
  apps/frontend/node_modules
  **/node_modules
  backup_day*
  venv
  .venv

rules:
  line-length:
    max: 120
    level: warning
  truthy: disable
  comments-indentation: disable
  document-start: disable
