extends: default

ignore: |
  **/node_modules
  venv
  .venv
  backup_day*

rules:
  line-length:
    max: 120
    level: warning
  truthy: disable
  comments-indentation: disable
  document-start: disable
