---
name: CI Lint

on:
  pull_request:
    branches:
      - dev

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Run yamllint on selected paths
        run: |
          yamllint \
            .github/workflows \
            deploy/compose \
            apps/orders-api \
            apps/ai-worker \
            docs
