name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f apps/orders-api/requirements.txt ]; then pip install -r apps/orders-api/requirements.txt; fi
      - run: flake8 apps || true
      - run: pytest -q || true

  build_and_scan:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: apps/orders-api
          file: apps/orders-api/Dockerfile
          push: false
          tags: local/orders-api:${{ github.sha }}
      - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL local/orders-api:${{ github.sha }} || true
      - run: docker run --rm -v "$(pwd)":/project -w /project aquasec/trivy:latest fs --exit-code 1 --severity HIGH,CRITICAL .
